// storybook/solid/stories/base/stores/Store.ts
import * as solid from "solid-js";
import { create } from "solid-gstatem";

type StateType = { count: number };

const initialState = { count: 0 };
const { useSelect, dispatch } = create<StateType>(solid, {
	state: initialState
});

/* the count hook for function component */
export const useCount = () => useSelect<number>(state => state.count);

/* increase the counter */
export const increaseCount = () =>
	dispatch(state => ({ count: state.count + 1 }));

/* reset counter */
export const resetCount = () => dispatch(initialState);

// storybook/react/stories/base/lib/Store.ts
import { create, Subscriber } from "react-gstatem";

export type StateType = { count: number };

const initialState = { count: 0 };
const Store = create<StateType>({ state: initialState });

const { useSelect, select, dispatch } = Store;

const countSelector = state => state.count;

/* select count hook for function component */
export const useCount = () => useSelect(countSelector);

/* select count for non function component */
export const selectCount = (subscribe: Subscriber<StateType>) =>
	select<number>(countSelector, subscribe);

/* update the store with callback */
export const increaseCount = () =>
	dispatch(state => ({ count: state.count + 1 }));

/* update the store with static value */
export const resetCount = () => dispatch(initialState);
